# Generated by Django 4.2.4 on 2023-10-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField()),
                ('archivo', models.FileField(upload_to='')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('puesto_deseado', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField()),
                ('agregado_el', models.DateTimeField(auto_now_add=True)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('VIUDO', 'Viudo')], default='SOLTERO', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_el', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('creado_el', models.DateTimeField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('es_primer_fase', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado_el', models.DateTimeField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
