# Generated by Django 4.2.4 on 2023-10-07 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fase',
            name='siguiente_fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.fase'),
        ),
        migrations.AddField(
            model_name='fase',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.tablero'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.candidato'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.fase'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tablero_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.tablero'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.candidato'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.fase'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='subido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
